### ISSUE TITLE
Image Class is not supported

### ISSUE THREAD

**Issue by OHR7** [nitinramadoss/image_compare#2]
im using your library and passing 2 images says that
"flutter: Unsupported operation: The source, Image, passed in is unsupported" 
which is funny since it says they are Image class any idea?

code 

    `var render = await this.widget.picture.toImage();
      try {

        print(render.runtimeType); // prints Image

        var result = await compareImages(
            src1: render,
            src2: render,
            algorithm: ChiSquareDistanceHistogram());

        print('The difference between images is: ${result * 100}%');
      } catch (e) {
        print(e);
      }`

**Comment by nitinramadoss** [comment]
This is a common package naming conflict. There are multiple `Image` classes in dart. Please check the [implementation](https://pub.dev/packages/image_compare#implementation) section of the docs and select the link for `Image` class. 

For others who face a similar issue, follow this [answer](https://stackoverflow.com/a/68156969/14881177) for a detailed solution.
