### ISSUE TITLE
PNG transparent issue

### ISSUE THREAD

**Issue by OHR7** [nitinramadoss/image_compare#3]
Hi the library is working fine but I need to use a PNG with transparency and when comparing it always returns 84.766%~ regardless of what I send, is there a setting that I can tweak to fix this issue?
NOTE im using a library to draw on the screen https://pub.dev/packages/painter
It works when I tweak the setting 

controller.backgroundColor = Colors.white; and the compare image with white background same PNG format, but when changing to 

controller.backgroundColor = Colors.transparent;  and using same image but removing the background and leaving it transparent it always return 84.766%~

```
  PainterController _controller = _newController();

  static PainterController _newController() {
    PainterController controller = new PainterController();
    controller.thickness = 15.0;
    controller.backgroundColor = Colors.transparent;
    return controller;
  }

  void _compare(PictureDetails picture, BuildContext context) async {
    try {
      var render = await picture.toImage();
      var data = await render.toByteData(format: ImageByteFormat.png);
      Uint8List img;
      if (data != null) {
        img = data.buffer.asUint8List();
      } else {
        throw new FlutterError('Flutter failed to convert an Image to bytes!');
      }

       // Recently changed to decodeImage() per stackoverflow suggestion but both work the same and have the same issue when using transparency

      // var image = dart_images.Image.fromBytes(200, 200, img);
      var image = dart_images.decodeImage(img);

      var secondImageData = await rootBundle.load('assets/transparent_img.png');
      var secondImageList = secondImageData.buffer.asUint8List();

      var result = await compareImages(
          src1: image,
          src2: secondImageList,
          algorithm: EuclideanColorDistance());
      print('The difference between images is: ${result * 100}%');
      setState(() {
        _percentage = result * 100;
      });
    } catch (e) {
      print(e);
    }
  }
```

**Comment by nitinramadoss** [comment]
Currently, the library does not have support for ignoring transparent pixel comparisons. The transparent pixels are treated as regular pixels: only their RGB values are used in the computations (no account for alpha channel). These pixels are black (RGB values of 0).

My suggestion is to compare the images but keep in mind that your result includes comparisons with the transparent pixels. You may also want to use a histogram comparison algorithm such as ChiSquareDistanceHistogram() or IntersectionHistogram().

Additionally, you may file a feature request for handling transparency.

**Comment by OHR7** [comment]
I'll have to talk with my team about it, maybe we can change the design to not use transparency, but will be better to have that feature if it is not that complicated to add, thanks for your response, best regards!

**Comment by nitinramadoss** [comment]
Feature in progress https://github.com/nitinramadoss/image_compare/pull/6

**Comment by nitinramadoss** [comment]
Feature is live
