### ISSUE TITLE
Issues with images, no difference found

### ISSUE THREAD

**Issue by axel-cln** [nitinramadoss/image_compare#5]
Hello, I have an issue with your package.
I want to compare some images from internet. However, when I compare these images, the result I get is 0.0 but there are differences between the images. The issue is maybe because the images are in black and white.

I tested all your algorithms and I always have a result equals to 0. 
I just had a good result when I used the algorithm ChiSquareDistanceHistogram to compare the images "one" and "two" (very low difference because the resultat was 1.3089300910883312e-24) but when I compared the images "two" and "three" the result was 0.

Can you please help me, maybe I don't understand something ?

I'm attaching pictures with which I have this issue.

Regards,
Axel

**Images that I use :**
One :
![one](https://user-images.githubusercontent.com/50293845/140663878-a4b82ba1-e6f8-45cf-9004-1dff589369c0.png)
Two :
![two](https://user-images.githubusercontent.com/50293845/140663877-6875d623-83da-4f3c-976c-d13b17213eae.png)
Three :
![three](https://user-images.githubusercontent.com/50293845/140663879-41bc699e-1e53-436a-b83e-bc785e712e88.png)

**Comment by nitinramadoss** [comment]
Hey there, thank you for bringing this to our attention! The algorithms return zero because transparent pixels are black pixels with 0 alpha. This means that those three images currently equate to images with only black pixels; therefore, the difference is zero. 

ChiSquareDistanceHistogram returns a non-zero result because of floating point error. 

We are working on a feature to handle transparent pixels and address #3

**Comment by axel-cln** [comment]
Hello, do you know when you will add this feature ?

Or do you know another solution to answer to my problematic ?
Initially, I wanted to compare the data bytes of each images but I had an issue with this.

Regards.

**Comment by nitinramadoss** [comment]
You should be able to compare the images for difference if the digits (1, 2 and 3) are in any color other than black.

The package automatically compares the bytes of the images. Each algorithm extracts the bytes first and then compares them with a unique strategy.

**Comment by axel-cln** [comment]
Hello, I found a solution to my problem.
I have succeeded to extract the bytes of the pictures, hash them and compare the hashcodes.

My initial goal was to verify if 2 pictures are exactly the same.
Here is my code to get the hash of a picture which is on internet if it can help someone :
```Dart
final response = await http.get(Uri.parse(pictureUrl));
var bytes = response.bodyBytes;
String imageHashcode = md5.convert(bytes).toString();
```

**Comment by nitinramadoss** [comment]
Feature in progress https://github.com/nitinramadoss/image_compare/pull/6
