### ISSUE TITLE
Make _getImageFromDynamic public

### ISSUE THREAD

**Issue by XuanTung95** [nitinramadoss/image_compare#7]
Thank you for the awesome package.
I used it for my tool to quickly find the icon from the screenshot.
But the screenshot is not transparent background like the icon, so I need a way to make these images have the same background.

It's nice if you can public _getImageFromDynamic so I can use it to get Image and apply some filter before comparing.

**Comment by krlaa** [comment]
Hey @XuanTung95 Sorry for the late response, thank you for using our package! Just to verify, you want to apply some filters to the image before the comparison correct?

**Comment by XuanTung95** [comment]
Hi @krlaa, Yes, I want to get the Image first, then apply filters to get Image2, then use Image2 to compare.

**Comment by krlaa** [comment]
@XuanTung95 Hey glad to hear back from you. In your situation we recommend you using the image library to apply your filters. Then pass that 'Image' object to our library. If you look at the documentation of our package the input source can be the type of 'Image'

**Comment by XuanTung95** [comment]
@krlaa yeah I know,
I want to use the _getImageFromDynamic() method from your library to get the Image first. Could you public it? 
The filter part is not related to this ticket.

**Comment by nitinramadoss** [comment]
Hey @XuanTung95, if you'd like to use some functionality from _getImageFromDynamic(), feel free to copy it from our repo. I'm closing this issue :) If you have any other questions, please feel free to file another issue or contact us directly!
